-- MySQL Script generated by MySQL Workbench
-- Wed Mar 28 18:53:47 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema BD_STC_PCL
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BD_STC_PCL
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BD_STC_PCL` DEFAULT CHARACTER SET utf8 ;
USE `BD_STC_PCL` ;

-- -----------------------------------------------------
-- Table `lineas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lineas` (
  `nom_linea` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`nom_linea`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `areas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `areas` (
  `nom_area` VARCHAR(25) NOT NULL,
  `nombre_linea` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`nom_area`),
  INDEX `fk_mando_centralizado_lineas1_idx` (`nombre_linea` ASC),
  CONSTRAINT `fk_mando_centralizado_lineas1`
    FOREIGN KEY (`nombre_linea`)
    REFERENCES `lineas` (`nom_linea`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `manuales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manuales` (
  `id_manual` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `codigo_manual` VARCHAR(45) NOT NULL,
  `descripcion` MEDIUMTEXT NOT NULL,
  `nom_equipo` VARCHAR(45) NULL,
  `tamanio` INT(100) UNSIGNED NOT NULL,
  `tipo_archivo` VARCHAR(200) NOT NULL,
  `nom_archivo` VARCHAR(200) NOT NULL,
  `area` VARCHAR(25) NOT NULL,
  `linea` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_manual`),
  INDEX `fk_manuales_lineas1_idx` (`linea` ASC),
  CONSTRAINT `fk_manuales_mando_centralizado1`
    FOREIGN KEY (`area`)
    REFERENCES `areas` (`nom_area`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_manuales_lineas1`
    FOREIGN KEY (`linea`)
    REFERENCES `lineas` (`nom_linea`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estaciones` (
  `id_estacion` INT NOT NULL AUTO_INCREMENT,
  `nombre_estacion` VARCHAR(25) NOT NULL,
  `nom_linea` VARCHAR(10) NOT NULL,
  INDEX `fk_estaciones_lineas1_idx` (`nom_linea` ASC),
  PRIMARY KEY (`id_estacion`),
  CONSTRAINT `fk_estaciones_lineas1`
    FOREIGN KEY (`nom_linea`)
    REFERENCES `lineas` (`nom_linea`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `planos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `planos` (
  `id_clave_planos` VARCHAR(100) NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `nombre_estacion` VARCHAR(25) NOT NULL,
  `nom_equipo` VARCHAR(45) NOT NULL,
  `area` VARCHAR(25) NOT NULL,
  `linea` VARCHAR(10) NOT NULL,
  `id_estacion` INT NOT NULL,
  PRIMARY KEY (`id_clave_planos`),
  INDEX `fk_planos_lineas1_idx` (`linea` ASC),
  INDEX `fk_planos_estaciones1_idx` (`id_estacion` ASC),
  CONSTRAINT `fk_manuales_mando_centralizado10`
    FOREIGN KEY (`area`)
    REFERENCES `areas` (`nom_area`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_planos_lineas1`
    FOREIGN KEY (`linea`)
    REFERENCES `lineas` (`nom_linea`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_planos_estaciones1`
    FOREIGN KEY (`id_estacion`)
    REFERENCES `estaciones` (`id_estacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `no_expediente` VARCHAR(10) NOT NULL,
  `nom_trabajador` VARCHAR(25) NOT NULL,
  `apellidos_trabajador` VARCHAR(25) NOT NULL,
  `nom_linea` VARCHAR(10) NOT NULL,
  `nombre_estacion` VARCHAR(25) NOT NULL,
  `id_estacion` INT NOT NULL,
  `nom_area` VARCHAR(25) NOT NULL,
  `categoria` VARCHAR(25) NOT NULL,
  `correo` VARCHAR(30) NOT NULL,
  `nom_usuario` VARCHAR(20) NOT NULL,
  `clave` VARCHAR(12) NOT NULL,
  `rol` INT(3) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_usuarios_estaciones1_idx` (`id_estacion` ASC),
  INDEX `fk_usuarios_lineas1_idx` (`nom_linea` ASC),
  CONSTRAINT `fk_usuarios_mando_centralizado1`
    FOREIGN KEY (`nom_area`)
    REFERENCES `areas` (`nom_area`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_usuarios_estaciones1`
    FOREIGN KEY (`id_estacion`)
    REFERENCES `estaciones` (`id_estacion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_usuarios_lineas1`
    FOREIGN KEY (`nom_linea`)
    REFERENCES `lineas` (`nom_linea`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `administrador` (
  `id_administrador` INT NOT NULL AUTO_INCREMENT,
  `no_expediente` VARCHAR(10) NOT NULL,
  `nom_administrador` VARCHAR(25) NOT NULL,
  `apellidos_administrador` VARCHAR(25) NOT NULL,
  `nom_linea` VARCHAR(10) NOT NULL,
  `nom_estacion` VARCHAR(25) NOT NULL,
  `id_estacion` INT NOT NULL,
  `nom_area` VARCHAR(25) NOT NULL,
  `categoria` VARCHAR(25) NOT NULL,
  `correo` VARCHAR(30) NOT NULL,
  `nom_usuario` VARCHAR(20) NOT NULL,
  `clave` VARCHAR(12) NOT NULL,
  `rol` INT(3) NOT NULL,
  PRIMARY KEY (`id_administrador`),
  INDEX `fk_administrador_lineas1_idx` (`nom_linea` ASC),
  INDEX `fk_administrador_areas1_idx` (`nom_area` ASC),
  INDEX `fk_administrador_estaciones1_idx` (`id_estacion` ASC),
  CONSTRAINT `fk_administrador_lineas1`
    FOREIGN KEY (`nom_linea`)
    REFERENCES `lineas` (`nom_linea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_administrador_areas1`
    FOREIGN KEY (`nom_area`)
    REFERENCES `areas` (`nom_area`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_administrador_estaciones1`
    FOREIGN KEY (`id_estacion`)
    REFERENCES `estaciones` (`id_estacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
